### 데이터 불러오기

In [9]:
#!pip install nba_api
#!pip install tabulate
from tabulate import tabulate

Requirement already satisfied: tabulate in c:\users\redtable\onedrive\kyungjun\.venv\lib\site-packages (0.9.0)

[notice] A new release of pip is available: 23.0.1 -> 23.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
import nba_api

In [5]:
encoding = "utf-8"
from nba_api.stats.static import players
#df = players.find_players_by_full_name("Russell Westbrook")
df = players.find_players_by_full_name("michael jordan")
#_first_name("russel")
print(df)

[{'id': 893, 'full_name': 'Michael Jordan', 'first_name': 'Michael', 'last_name': 'Jordan', 'is_active': False}]

In [6]:
from nba_api.stats.endpoints import commonplayerinfo

player_info = commonplayerinfo.CommonPlayerInfo(player_id=893)#)201566)
test = player_info.get_data_frames()
test[0].head()
#test[1].head()

   PERSON_ID FIRST_NAME LAST_NAME  ... DRAFT_ROUND DRAFT_NUMBER GREATEST_75_FLAG
0        893    Michael    Jordan  ...           1            3                Y

[1 rows x 33 columns]

In [7]:
from nba_api.stats.endpoints import playercareerstats

career = playercareerstats.PlayerCareerStats(player_id=893)#'201566')
temp = career.get_data_frames()
temp[0]

    PLAYER_ID SEASON_ID LEAGUE_ID     TEAM_ID  ...  BLK  TOV   PF   PTS
0         893   1984-85        00  1610612741  ...   69  291  285  2313
1         893   1985-86        00  1610612741  ...   21   45   46   408
2         893   1986-87        00  1610612741  ...  125  272  237  3041
3         893   1987-88        00  1610612741  ...  131  252  270  2868
4         893   1988-89        00  1610612741  ...   65  290  247  2633
5         893   1989-90        00  1610612741  ...   54  247  241  2753
6         893   1990-91        00  1610612741  ...   83  202  229  2580
7         893   1991-92        00  1610612741  ...   75  200  201  2404
8         893   1992-93        00  1610612741  ...   61  207  188  2541
9         893   1994-95        00  1610612741  ...   13   35   47   457
10        893   1995-96        00  1610612741  ...   42  197  195  2491
11        893   1996-97        00  1610612741  ...   44  166  156  2431
12        893   1997-98        00  1610612741  ...   45  185  151  2357
13        893   2001-02        00  1610612764  ...   26  162  119  1375
14        893   2002-03        00  1610612764  ...   39  173  171  1640

[15 rows x 27 columns]

In [10]:
print(tabulate(temp[0], headers='keys', tablefmt='psql', showindex=True))

+----+-------------+-------------+-------------+------------+---------------------+--------------+------+------+-------+-------+-------+----------+--------+--------+-----------+-------+-------+----------+--------+--------+-------+-------+-------+-------+-------+------+-------+
|    |   PLAYER_ID | SEASON_ID   |   LEAGUE_ID |    TEAM_ID | TEAM_ABBREVIATION   |   PLAYER_AGE |   GP |   GS |   MIN |   FGM |   FGA |   FG_PCT |   FG3M |   FG3A |   FG3_PCT |   FTM |   FTA |   FT_PCT |   OREB |   DREB |   REB |   AST |   STL |   BLK |   TOV |   PF |   PTS |
|----+-------------+-------------+-------------+------------+---------------------+--------------+------+------+-------+-------+-------+----------+--------+--------+-----------+-------+-------+----------+--------+--------+-------+-------+-------+-------+-------+------+-------|
|  0 |         893 | 1984-85     |          00 | 1610612741 | CHI                 |           22 |   82 |   82 |  3144 |   837 |  1625 |    0.515 |      9 |     52 |     0.173 |   630 |   746 |    0.845 |    167 |    367 |   534 |   481 |   196 |    69 |   291 |  285 |  2313 |
|  1 |         893 | 1985-86     |          00 | 1610612741 | CHI                 |           23 |   18 |    7 |   451 |   150 |   328 |    0.457 |      3 |     18 |     0.167 |   105 |   125 |    0.84  |     23 |     41 |    64 |    53 |    37 |    21 |    45 |   46 |   408 |
|  2 |         893 | 1986-87     |          00 | 1610612741 | CHI                 |           24 |   82 |   82 |  3281 |  1098 |  2279 |    0.482 |     12 |     66 |     0.182 |   833 |   972 |    0.857 |    166 |    264 |   430 |   377 |   236 |   125 |   272 |  237 |  3041 |
|  3 |         893 | 1987-88     |          00 | 1610612741 | CHI                 |           25 |   82 |   82 |  3311 |  1069 |  1998 |    0.535 |      7 |     53 |     0.132 |   723 |   860 |    0.841 |    139 |    310 |   449 |   485 |   259 |   131 |   252 |  270 |  2868 |
|  4 |         893 | 1988-89     |          00 | 1610612741 | CHI                 |           26 |   81 |   81 |  3255 |   966 |  1795 |    0.538 |     27 |     98 |     0.276 |   674 |   793 |    0.85  |    149 |    503 |   652 |   650 |   234 |    65 |   290 |  247 |  2633 |
|  5 |         893 | 1989-90     |          00 | 1610612741 | CHI                 |           27 |   82 |   82 |  3197 |  1034 |  1964 |    0.526 |     92 |    245 |     0.376 |   593 |   699 |    0.848 |    143 |    422 |   565 |   519 |   227 |    54 |   247 |  241 |  2753 |
|  6 |         893 | 1990-91     |          00 | 1610612741 | CHI                 |           28 |   82 |   82 |  3034 |   990 |  1837 |    0.539 |     29 |     93 |     0.312 |   571 |   671 |    0.851 |    118 |    374 |   492 |   453 |   223 |    83 |   202 |  229 |  2580 |
|  7 |         893 | 1991-92     |          00 | 1610612741 | CHI                 |           29 |   80 |   80 |  3102 |   943 |  1818 |    0.519 |     27 |    100 |     0.27  |   491 |   590 |    0.832 |     91 |    420 |   511 |   489 |   182 |    75 |   200 |  201 |  2404 |
|  8 |         893 | 1992-93     |          00 | 1610612741 | CHI                 |           30 |   78 |   78 |  3067 |   992 |  2003 |    0.495 |     81 |    230 |     0.352 |   476 |   569 |    0.837 |    135 |    387 |   522 |   428 |   221 |    61 |   207 |  188 |  2541 |
|  9 |         893 | 1994-95     |          00 | 1610612741 | CHI                 |           32 |   17 |   17 |   668 |   166 |   404 |    0.411 |     16 |     32 |     0.5   |   109 |   136 |    0.801 |     25 |     92 |   117 |    90 |    30 |    13 |    35 |   47 |   457 |
| 10 |         893 | 1995-96     |          00 | 1610612741 | CHI                 |           33 |   82 |   82 |  3090 |   916 |  1850 |    0.495 |    111 |    260 |     0.427 |   548 |   657 |    0.834 |    148 |    395 |   543 |   352 |   180 |    42 |   197 |  195 |  2491 |
| 11 |         893 | 1996-97     |          00 | 1610612741 | CHI                 |           34 |   82 |   82 |  3109 |   920 |  1892 |    0.486 |    111 |    297 |     0.374 |   480 |   576 |    0.833 |    113 |    369 |   482 |   352 |   140 |    44 |   166 |  156 |  2431 |
| 12 |         893 | 1997-98     |          00 | 1610612741 | CHI                 |           35 |   82 |   82 |  3181 |   881 |  1893 |    0.465 |     30 |    126 |     0.238 |   565 |   721 |    0.784 |    130 |    345 |   475 |   283 |   141 |    45 |   185 |  151 |  2357 |
| 13 |         893 | 2001-02     |          00 | 1610612764 | WAS                 |           39 |   60 |   53 |  2089 |   551 |  1324 |    0.416 |     10 |     53 |     0.189 |   263 |   333 |    0.79  |     50 |    289 |   339 |   310 |    85 |    26 |   162 |  119 |  1375 |
| 14 |         893 | 2002-03     |          00 | 1610612764 | WAS                 |           40 |   82 |   67 |  3029 |   679 |  1527 |    0.445 |     16 |     55 |     0.291 |   266 |   324 |    0.821 |     71 |    426 |   497 |   311 |   123 |    39 |   173 |  171 |  1640 |
+----+-------------+-------------+-------------+------------+---------------------+--------------+------+------+-------+-------+-------+----------+--------+--------+-----------+-------+-------+----------+--------+--------+-------+-------+-------+-------+-------+------+-------+

In [18]:
from nba_api.live.nba.endpoints import scoreboard

# Today's Score Board
games = scoreboard.ScoreBoard()

# json
games.get_json()

# dictionary
games.get_dict()

{'meta': {'version': 1,
  'request': 'https://nba-prod-us-east-1-mediaops-stats.s3.amazonaws.com/NBA/liveData/scoreboard/todaysScoreboard_00.json',
  'time': '2023-04-24 01:45:32.4532',
  'code': 200},
 'scoreboard': {'gameDate': '2023-04-23',
  'leagueId': '00',
  'leagueName': 'National Basketball Association',
  'games': [{'gameId': '0042200134',
    'gameCode': '20230423/CLENYK',
    'gameStatus': 3,
    'gameStatusText': 'Final',
    'period': 4,
    'gameClock': '',
    'gameTimeUTC': '2023-04-23T17:00:00Z',
    'gameEt': '2023-04-23T13:00:00Z',
    'regulationPeriods': 4,
    'ifNecessary': False,
    'seriesGameNumber': 'Game 4',
    'seriesText': 'NYK leads 3-1',
    'seriesConference': 'East',
    'poRoundDesc': 'First Round',
    'gameSubtype': '',
    'homeTeam': {'teamId': 1610612752,
     'teamName': 'Knicks',
     'teamCity': 'New York',
     'teamTricode': 'NYK',
     'wins': 3,
     'losses': 1,
     'score': 102,
     'seed': 5,
     'inBonus': None,
     'timeoutsRemaining': 1,
     'periods': [{'period': 1, 'periodType': 'REGULAR', 'score': 30},
      {'period': 2, 'periodType': 'REGULAR', 'score': 24},
      {'period': 3, 'periodType': 'REGULAR', 'score': 19},
      {'period': 4, 'periodType': 'REGULAR', 'score': 29}]},
    'awayTeam': {'teamId': 1610612739,
     'teamName': 'Cavaliers',
     'teamCity': 'Cleveland',
     'teamTricode': 'CLE',
     'wins': 1,
     'losses': 3,
     'score': 93,
     'seed': 4,
     'inBonus': None,
     'timeoutsRemaining': 0,
     'periods': [{'period': 1, 'periodType': 'REGULAR', 'score': 23},
      {'period': 2, 'periodType': 'REGULAR', 'score': 22},
      {'period': 3, 'periodType': 'REGULAR', 'score': 26},
      {'period': 4, 'periodType': 'REGULAR', 'score': 22}]},
    'gameLeaders': {'homeLeaders': {'personId': 1628973,
      'name': 'Jalen Brunson',
      'jerseyNum': '11',
      'position': 'G',
      'teamTricode': 'NYK',
      'playerSlug': None,
      'points': 29,
      'rebounds': 6,
      'assists': 6},
     'awayLeaders': {'personId': 1629636,
      'name': 'Darius Garland',
      'jerseyNum': '10',
      'position': 'G',
      'teamTricode': 'CLE',
      'playerSlug': None,
      'points': 23,
      'rebounds': 2,
      'assists': 10}},
    'pbOdds': {'team': None, 'odds': 0.0, 'suspended': 0}},
   {'gameId': '0042200164',
    'gameCode': '20230423/SACGSW',
    'gameStatus': 3,
    'gameStatusText': 'Final',
    'period': 4,
    'gameClock': '',
    'gameTimeUTC': '2023-04-23T19:30:00Z',
    'gameEt': '2023-04-23T15:30:00Z',
    'regulationPeriods': 4,
    'ifNecessary': False,
    'seriesGameNumber': 'Game 4',
    'seriesText': 'Series tied 2-2',
    'seriesConference': 'West',
    'poRoundDesc': 'First Round',
    'gameSubtype': '',
    'homeTeam': {'teamId': 1610612744,
     'teamName': 'Warriors',
     'teamCity': 'Golden State',
     'teamTricode': 'GSW',
     'wins': 2,
     'losses': 2,
     'score': 126,
     'seed': 6,
     'inBonus': None,
     'timeoutsRemaining': 0,
     'periods': [{'period': 1, 'periodType': 'REGULAR', 'score': 31},
      {'period': 2, 'periodType': 'REGULAR', 'score': 34},
      {'period': 3, 'periodType': 'REGULAR', 'score': 37},
      {'period': 4, 'periodType': 'REGULAR', 'score': 24}]},
    'awayTeam': {'teamId': 1610612758,
     'teamName': 'Kings',
     'teamCity': 'Sacramento',
     'teamTricode': 'SAC',
     'wins': 2,
     'losses': 2,
     'score': 125,
     'seed': 3,
     'inBonus': None,
     'timeoutsRemaining': 0,
     'periods': [{'period': 1, 'periodType': 'REGULAR', 'score': 32},
      {'period': 2, 'periodType': 'REGULAR', 'score': 37},
      {'period': 3, 'periodType': 'REGULAR', 'score': 23},
      {'period': 4, 'periodType': 'REGULAR', 'score': 33}]},
    'gameLeaders': {'homeLeaders': {'personId': 201939,
      'name': 'Stephen Curry',
      'jerseyNum': '30',
      'position': 'G',
      'teamTricode': 'GSW',
      'playerSlug': None,
      'points': 32,
      'rebounds': 5,
      'assists': 4},
     'awayLeaders': {'personId': 1628368,
      'name': "De'Aaron Fox",
      'jerseyNum': '5',
      'position': 'G',
      'teamTricode': 'SAC',
      'playerSlug': None,
      'points': 38,
      'rebounds': 9,
      'assists': 5}},
    'pbOdds': {'team': None, 'odds': 0.0, 'suspended': 0}},
   {'gameId': '0042200114',
    'gameCode': '20230423/BOSATL',
    'gameStatus': 3,
    'gameStatusText': 'Final',
    'period': 4,
    'gameClock': '',
    'gameTimeUTC': '2023-04-23T23:00:00Z',
    'gameEt': '2023-04-23T19:00:00Z',
    'regulationPeriods': 4,
    'ifNecessary': False,
    'seriesGameNumber': 'Game 4',
    'seriesText': 'BOS leads 3-1',
    'seriesConference': 'East',
    'poRoundDesc': 'First Round',
    'gameSubtype': '',
    'homeTeam': {'teamId': 1610612737,
     'teamName': 'Hawks',
     'teamCity': 'Atlanta',
     'teamTricode': 'ATL',
     'wins': 1,
     'losses': 3,
     'score': 121,
     'seed': 7,
     'inBonus': None,
     'timeoutsRemaining': 1,
     'periods': [{'period': 1, 'periodType': 'REGULAR', 'score': 25},
      {'period': 2, 'periodType': 'REGULAR', 'score': 28},
      {'period': 3, 'periodType': 'REGULAR', 'score': 34},
      {'period': 4, 'periodType': 'REGULAR', 'score': 34}]},
    'awayTeam': {'teamId': 1610612738,
     'teamName': 'Celtics',
     'teamCity': 'Boston',
     'teamTricode': 'BOS',
     'wins': 3,
     'losses': 1,
     'score': 129,
     'seed': 2,
     'inBonus': None,
     'timeoutsRemaining': 1,
     'periods': [{'period': 1, 'periodType': 'REGULAR', 'score': 35},
      {'period': 2, 'periodType': 'REGULAR', 'score': 30},
      {'period': 3, 'periodType': 'REGULAR', 'score': 27},
      {'period': 4, 'periodType': 'REGULAR', 'score': 37}]},
    'gameLeaders': {'homeLeaders': {'personId': 1629027,
      'name': 'Trae Young',
      'jerseyNum': '11',
      'position': 'G',
      'teamTricode': 'ATL',
      'playerSlug': None,
      'points': 35,
      'rebounds': 3,
      'assists': 15},
     'awayLeaders': {'personId': 1628369,
      'name': 'Jayson Tatum',
      'jerseyNum': '0',
      'position': 'F-G',
      'teamTricode': 'BOS',
      'playerSlug': None,
      'points': 31,
      'rebounds': 7,
      'assists': 4}},
    'pbOdds': {'team': None, 'odds': 0.0, 'suspended': 0}},
   {'gameId': '0042200144',
    'gameCode': '20230423/DENMIN',
    'gameStatus': 3,
    'gameStatusText': 'Final/OT',
    'period': 5,
    'gameClock': '',
    'gameTimeUTC': '2023-04-24T01:30:00Z',
    'gameEt': '2023-04-23T21:30:00Z',
    'regulationPeriods': 4,
    'ifNecessary': False,
    'seriesGameNumber': 'Game 4',
    'seriesText': 'DEN leads 3-1',
    'seriesConference': 'West',
    'poRoundDesc': 'First Round',
    'gameSubtype': '',
    'homeTeam': {'teamId': 1610612750,
     'teamName': 'Timberwolves',
     'teamCity': 'Minnesota',
     'teamTricode': 'MIN',
     'wins': 1,
     'losses': 3,
     'score': 114,
     'seed': 8,
     'inBonus': None,
     'timeoutsRemaining': 1,
     'periods': [{'period': 1, 'periodType': 'REGULAR', 'score': 23},
      {'period': 2, 'periodType': 'REGULAR', 'score': 25},
      {'period': 3, 'periodType': 'REGULAR', 'score': 32},
      {'period': 4, 'periodType': 'REGULAR', 'score': 16},
      {'period': 5, 'periodType': 'OVERTIME', 'score': 18}]},
    'awayTeam': {'teamId': 1610612743,
     'teamName': 'Nuggets',
     'teamCity': 'Denver',
     'teamTricode': 'DEN',
     'wins': 3,
     'losses': 1,
     'score': 108,
     'seed': 1,
     'inBonus': None,
     'timeoutsRemaining': 0,
     'periods': [{'period': 1, 'periodType': 'REGULAR', 'score': 22},
      {'period': 2, 'periodType': 'REGULAR', 'score': 30},
      {'period': 3, 'periodType': 'REGULAR', 'score': 22},
      {'period': 4, 'periodType': 'REGULAR', 'score': 22},
      {'period': 5, 'periodType': 'OVERTIME', 'score': 12}]},
    'gameLeaders': {'homeLeaders': {'personId': 1630162,
      'name': 'Anthony Edwards',
      'jerseyNum': '1',
      'position': 'G',
      'teamTricode': 'MIN',
      'playerSlug': None,
      'points': 34,
      'rebounds': 6,
      'assists': 5},
     'awayLeaders': {'personId': 203999,
      'name': 'Nikola Jokic',
      'jerseyNum': '15',
      'position': 'C',
      'teamTricode': 'DEN',
      'playerSlug': None,
      'points': 43,
      'rebounds': 11,
      'assists': 6}},
    'pbOdds': {'team': None, 'odds': 0.0, 'suspended': 0}}]}}